revert partial treewide commit fs/f2fs/data.c broke compilation :
  CC      fs/f2fs/data.o
/Ginkgo-Vikingo/fs/f2fs/data.c:159:6: error: use of undeclared identifier 'first_page'
        if (first_page != NULL &&
            ^
/Ginkgo-Vikingo/fs/f2fs/data.c:160:18: error: use of undeclared identifier 'first_page'
                __read_io_type(first_page) == F2FS_RD_DATA) {
                               ^
/Ginkgo-Vikingo/fs/f2fs/data.c:162:19: error: use of undeclared identifier 'first_page'
                                                page_offset(first_page),
                                                            ^
/Ginkgo-Vikingo/fs/f2fs/data.c:161:33: error: use of undeclared identifier 'first_page'
                trace_android_fs_dataread_end(first_page->mapping->host,
                                              ^
4 errors generated.
make[3]: *** [/Ginkgo-Vikingo/scripts/Makefile.build:361: fs/f2fs/data.o] Error 1
make[2]: *** [/Ginkgo-Vikingo/scripts/Makefile.build:676: fs/f2fs] Error 2
make[1]: *** [/Ginkgo-Vikingo/Makefile:1145: fs] Error 2
make[1]: *** Waiting for unfinished jobs....

Signed-off-by: Carlos Jimenez (JavaShin-X) <javashin1986@gmail.com>